import Navbar from "./components/Navbar";
import ProfilePic from "./components/ProfilePic";
import "./globals.css";

export const metadata = {
  title: "Personal Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-cyan-900 text-white/90">
        <Navbar />
        <ProfilePic />
        {children}
      </body>
    </html>
  );
}
